"""plants table

Revision ID: 07716bd40f49
Revises: 4cb78415e508
Create Date: 2018-03-21 18:41:23.318205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07716bd40f49'
down_revision = '4cb78415e508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_timestamp'), 'plant', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_timestamp'), table_name='plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
