"""empty message

Revision ID: 131e34f63026
Revises: 11b48b89e54d
Create Date: 2018-03-23 15:00:20.994509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131e34f63026'
down_revision = '11b48b89e54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
