"""users_gardens table

Revision ID: 353a4b520437
Revises: d535bad55c95
Create Date: 2018-04-06 16:32:38.831190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353a4b520437'
down_revision = 'd535bad55c95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_gardens',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_gardens')
    # ### end Alembic commands ###
