"""Add address, lat, and lon rows to Garden table

Revision ID: 3ec18dbfc7ff
Revises: e2e1f8a5ec63
Create Date: 2018-05-17 15:24:43.063924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec18dbfc7ff'
down_revision = 'e2e1f8a5ec63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garden', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('garden', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('garden', sa.Column('lon', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_garden_address'), 'garden', ['address'], unique=False)
    op.create_index(op.f('ix_garden_lat'), 'garden', ['lat'], unique=False)
    op.create_index(op.f('ix_garden_lon'), 'garden', ['lon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_garden_lon'), table_name='garden')
    op.drop_index(op.f('ix_garden_lat'), table_name='garden')
    op.drop_index(op.f('ix_garden_address'), table_name='garden')
    op.drop_column('garden', 'lon')
    op.drop_column('garden', 'lat')
    op.drop_column('garden', 'address')
    # ### end Alembic commands ###
