"""Add self referential relationship to Post table to allow for replies to posts.

Revision ID: 5aebc5627d45
Revises: 74e2ee3111f3
Create Date: 2019-05-26 17:12:10.322263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aebc5627d45'
down_revision = '74e2ee3111f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reply_post', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'post', 'post', ['parent_comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'reply_post')
    op.drop_column('post', 'parent_comment_id')
    # ### end Alembic commands ###
