"""Add wall_post (boolean) and wall_owner_id (integer) columns to post table to allow for posting onto a user's wall. This should allow making new posts that are posts to a user's wall, getting the current user's wall, and getting another user's wall.

Revision ID: 74e2ee3111f3
Revises: bb5ed0594ba7
Create Date: 2019-04-03 18:10:49.941721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e2ee3111f3'
down_revision = 'bb5ed0594ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('wall_owner_id', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('wall_post', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'wall_post')
    op.drop_column('post', 'wall_owner_id')
    # ### end Alembic commands ###
