"""user tokens

Revision ID: bb5ed0594ba7
Revises: 3ec18dbfc7ff
Create Date: 2018-06-13 21:54:36.866578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5ed0594ba7'
down_revision = '3ec18dbfc7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_garden_address'), 'garden', ['address'], unique=False)
    op.create_index(op.f('ix_garden_lat'), 'garden', ['lat'], unique=False)
    op.create_index(op.f('ix_garden_lon'), 'garden', ['lon'], unique=False)
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    op.drop_index(op.f('ix_garden_lon'), table_name='garden')
    op.drop_index(op.f('ix_garden_lat'), table_name='garden')
    op.drop_index(op.f('ix_garden_address'), table_name='garden')
    # ### end Alembic commands ###
