"""add back garden and plant tables with correct columns and garden/plant relationship added, since sqlite cannot handle alter table requests

Revision ID: d535bad55c95
Revises: 8d2523fee7bd
Create Date: 2018-04-03 17:32:40.924010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd535bad55c95'
down_revision = '8d2523fee7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garden_created'), 'garden', ['created'], unique=False)
    op.create_index(op.f('ix_garden_name'), 'garden', ['name'], unique=False)
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('garden_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garden_id'], ['garden.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_timestamp'), 'plant', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_timestamp'), table_name='plant')
    op.drop_table('plant')
    op.drop_index(op.f('ix_garden_name'), table_name='garden')
    op.drop_index(op.f('ix_garden_created'), table_name='garden')
    op.drop_table('garden')
    # ### end Alembic commands ###
